base_url = "https://boka.techbuddy.io/#/login"
correct_mobile_number = "46701234567"
incorrect_mobile_number_digits = "111"
incorrect_mobile_number_alphabetical = "aaa"
correct_sms_code = "100100"
incorrect_sms_code = "111"
sample_text = "sample text"
